# Generated by Django 4.1.5 on 2023-04-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3000', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='discrition',
            field=models.CharField(max_length=5000),
        ),
    ]
